
backend:
  name: github
  repo: DROPTASK/stellar-project-vision
  branch: main
  auth_type: implicit
  app_id: null # Replace with your GitHub OAuth app ID if needed

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Explore Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Funding", name: "funding", widget: "string", required: false }
      - { label: "Reward", name: "reward", widget: "string", required: false }
      - { label: "TGE", name: "tge", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "text", required: false }
