backend:
  name: github
  repo: DROPTASK/stellar-project-vision  # your GitHub repo
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Link", name: "link", widget: "string" }
