// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmgovrqtmtdskbgsnnkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptZ292cnF0bXRkc2tiZ3NubmtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2OTE3MzAsImV4cCI6MjA2NDI2NzczMH0.ftMqvdeSlrfh3RBAKPCndwcKufA0h9P_9oq1RQ0dGIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);